### ISSUE TITLE
server: server_data payload sent to clients is incomplete

### ISSUE THREAD

**Issue by extremeheat** [PrismarineJS/node-minecraft-protocol#1362]
https://github.com/PrismarineJS/node-minecraft-protocol/blob/f258c76b3a15badd902e82cd892168849444d79d/src/server/login.js#L199-L203 doesn't send correct payload for 1.19+

1.19
```yaml
   packet_server_data:   
      motd?: string
      icon?: string
      previewsChat: bool
```

1.19.2
```yaml
   packet_server_data:   
      motd?: string
      icon?: string
      previewsChat: bool
      enforcesSecureChat: bool
```

1.19.3
```yaml
   packet_server_data:   
      motd?: string
      icon?: string
      enforcesSecureChat: bool
```

1.19.4, 1.20, 1.20.2
```yaml
   packet_server_data:   
      motd: string
      iconBytes?: [
         "buffer",
         {
            "countType": "varint"
         }
      ]
      enforcesSecureChat: bool
```

1.20.3
```yaml
   packet_server_data:
      motd: anonymousNbt
      iconBytes?: [
         "buffer",
         {
            "countType": "varint"
         }
      ]
      enforcesSecureChat: bool
```

1.20.5+
```yaml
   # MC: ClientboundServerDataPacket
   packet_server_data:
      motd: anonymousNbt
      iconBytes?: ByteArray
```

Check
* Did `icon` actually change from string to buffer
* verify motd went optional string -> required string -> nbt (probably caused by JSON chat component to NBT)

Not breaking anything currently though, interestingly
